swagger: '2.0'
info:
  version: "0.0.1"
  title: Please navigate to synack.com for password reset
  description: Please navigate to synack.com for password reset
paths:
  /:
    get:
      responses:
        200:
          description: Success
